# Generated by Django 3.2.19 on 2023-07-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='cost',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='historicalcost',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='historicallot',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='historicallotcost',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='historicalorder',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='lotcost',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='productinwarehouse',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('paid', 'оплачен'), ('not_paid', 'не оплачен'), ('shipped', 'отгружен')], default='new', max_length=32, verbose_name='Статус покупки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('paid', 'оплачен'), ('not_paid', 'не оплачен'), ('shipped', 'отгружен')], default='new', max_length=32, verbose_name='Статус покупки'),
        ),
        migrations.AlterField(
            model_name='productinwarehouse',
            name='transaction',
            field=models.CharField(choices=[('in', 'получение'), ('out', 'отгрузка'), ('return', 'возврат'), ('write_off', 'списание')], max_length=10, verbose_name='Транзакция'),
        ),
    ]
