# Generated by Django 3.2.19 on 2023-06-11 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcredit',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical credit'},
        ),
        migrations.AlterModelOptions(
            name='historicaldebit',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical debit'},
        ),
        migrations.AlterModelOptions(
            name='historicallot',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical lot'},
        ),
        migrations.AlterModelOptions(
            name='historicallotcost',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical lot cost'},
        ),
        migrations.AlterModelOptions(
            name='historicalorder',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical order'},
        ),
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical product'},
        ),
        migrations.AlterModelOptions(
            name='historicalproductinlot',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical product in lot'},
        ),
        migrations.AlterModelOptions(
            name='historicalproductinorder',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical product in order'},
        ),
        migrations.AlterField(
            model_name='debit',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='historicalcredit',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaldebit',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaldebit',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('paid', 'оплачен'), ('delivered', 'доставлен'), ('delivered_to_warehouse', 'доставлен на склад')], default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicallotcost',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('paid', 'оплачен'), ('shipped', 'отправлен')], default='new', max_length=32, verbose_name='Статус покупки'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalproductinlot',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalproductinlot',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='historicalproductinorder',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('paid', 'оплачен'), ('delivered', 'доставлен'), ('delivered_to_warehouse', 'доставлен на склад')], default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('paid', 'оплачен'), ('shipped', 'отправлен')], default='new', max_length=32, verbose_name='Статус покупки'),
        ),
        migrations.AlterField(
            model_name='productinlot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Товар'),
        ),
        migrations.DeleteModel(
            name='HistoricalProductInWarehouse',
        ),
    ]
