# Generated by Django 3.2.19 on 2023-07-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20230705_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='cost',
            name='transaction',
            field=models.CharField(choices=[('in', 'приход'), ('out', 'расход')], max_length=10, verbose_name='Вид прихода'),
        ),
        migrations.AlterField(
            model_name='historicalcost',
            name='transaction',
            field=models.CharField(choices=[('in', 'приход'), ('out', 'расход')], max_length=10, verbose_name='Вид прихода'),
        ),
    ]
